// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/components/overflow":{"path":"components/overflow","id":"docs/components/overflow","parentId":"DocLayout"},"docs/study/typescript":{"path":"study/typescript","id":"docs/study/typescript","parentId":"DocLayout"},"docs/study/canvas":{"path":"study/canvas","id":"docs/study/canvas","parentId":"DocLayout"},"docs/docs/index":{"path":"docs","id":"docs/docs/index","parentId":"DocLayout"},"docs/study/html":{"path":"study/html","id":"docs/study/html","parentId":"DocLayout"},"docs/study/css":{"path":"study/css","id":"docs/study/css","parentId":"DocLayout"},"docs/study/git":{"path":"study/git","id":"docs/study/git","parentId":"DocLayout"},"docs/docs/faq":{"path":"docs/faq","id":"docs/docs/faq","parentId":"DocLayout"},"docs/study/js":{"path":"study/js","id":"docs/study/js","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/Button/index":{"id":"components/Button/index","path":"components/button","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/koolearn/Documents/dfzx/demo/monorepo/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.5_@types+node@20.19.25_@types+react@18.3.27_@types+webpack@5.28._itlth56nxjkbb5ovvoeenjhrou/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */'/Users/koolearn/Documents/dfzx/demo/monorepo/.dumi/tmp-production/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/koolearn/Documents/dfzx/demo/monorepo/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.5_@types+node@20.19.25_@types+react@18.3.27_@types+webpack@5.28._itlth56nxjkbb5ovvoeenjhrou/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/components/overflow': React.lazy(() => import(/* webpackChunkName: "docs__components__overflow.md" */'/Users/koolearn/Documents/dfzx/demo/monorepo/docs/components/overflow.md')),
'docs/study/typescript': React.lazy(() => import(/* webpackChunkName: "docs__study__typescript.md" */'/Users/koolearn/Documents/dfzx/demo/monorepo/docs/study/typescript.md')),
'docs/study/canvas': React.lazy(() => import(/* webpackChunkName: "docs__study__canvas.md" */'/Users/koolearn/Documents/dfzx/demo/monorepo/docs/study/canvas.md')),
'docs/docs/index': React.lazy(() => import(/* webpackChunkName: "docs__docs__index.md" */'/Users/koolearn/Documents/dfzx/demo/monorepo/docs/docs/index.md')),
'docs/study/html': React.lazy(() => import(/* webpackChunkName: "docs__study__html.md" */'/Users/koolearn/Documents/dfzx/demo/monorepo/docs/study/html.md')),
'docs/study/css': React.lazy(() => import(/* webpackChunkName: "docs__study__css.md" */'/Users/koolearn/Documents/dfzx/demo/monorepo/docs/study/css.md')),
'docs/study/git': React.lazy(() => import(/* webpackChunkName: "docs__study__git.md" */'/Users/koolearn/Documents/dfzx/demo/monorepo/docs/study/git.md')),
'docs/docs/faq': React.lazy(() => import(/* webpackChunkName: "docs__docs__faq.md" */'/Users/koolearn/Documents/dfzx/demo/monorepo/docs/docs/faq.md')),
'docs/study/js': React.lazy(() => import(/* webpackChunkName: "docs__study__js.md" */'/Users/koolearn/Documents/dfzx/demo/monorepo/docs/study/js.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/koolearn/Documents/dfzx/demo/monorepo/docs/index.md')),
'components/Button/index': React.lazy(() => import(/* webpackChunkName: "packages__components__src__Button__index.md" */'/Users/koolearn/Documents/dfzx/demo/monorepo/packages/components/src/Button/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/koolearn/Documents/dfzx/demo/monorepo/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.5_@types+node@20.19.25_@types+react@18.3.27_@types+webpack@5.28._itlth56nxjkbb5ovvoeenjhrou/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
