// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/koolearn/Documents/dfzx/demo/monorepo/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.5_@types+node@20.19.25_@types+react@18.3.27_@types+webpack@5.28._itlth56nxjkbb5ovvoeenjhrou/node_modules/dumi/theme-default/slots/Toc/index.js';
