// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import nprogress from '/Users/koolearn/Documents/dfzx/demo/monorepo/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress';
import './nprogress.css';
import UserLoading from '/Users/koolearn/Documents/dfzx/demo/monorepo/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.5_@types+node@20.19.25_@types+react@18.3.27_@types+webpack@5.28._itlth56nxjkbb5ovvoeenjhrou/node_modules/dumi/dist/client/pages/Loading';
import React, { useLayoutEffect, type FC } from 'react';
import { useSiteData } from 'dumi';

const DumiLoading: FC = () => {
  const { setLoading } = useSiteData();

  useLayoutEffect(() => {
    setLoading(true);
    nprogress.start();

    return () => {
      setLoading(false);
      nprogress.done();
    }
  }, []);

  return <UserLoading />
}

export default DumiLoading;
